version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Install SBT Repo
          command: 'echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list'
      - run:
          name: Install PGP Key for SBT Repo
          command: 'sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823'
      - run:
          name: Install SBT
          command: 'sudo apt install apt-transport-https && sudo apt update && sudo apt install sbt'
      - run:
          name: Run Test Suite
          command: 'sbt test'

